version: '3.8'

services:
  backend:
    image: python:3.10
    container_name: flask-api
    command: gunicorn --bind 0.0.0.0:5000 app.main:app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      - nginx
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
